---
- name: install devstack
  hosts: localhost
  vars_files:
  - customize.yml
  remote_user: "{{ username }}"
  tasks:

  - name: clone devstack
    git: repo=https://github.com/openstack-dev/devstack.git
         dest=~/devstack
         version={{ branch }}

  - name: devstack local.conf
    template: src=templates/devstack-local.conf.j2
              dest=~/devstack/local.conf

  - name: stack it
    command: chdir=~/devstack ./stack.sh
    ignore_errors: yes

  - name: unstack it
    command: chdir=~/devstack ./unstack.sh

  - name: restack it
    command: chdir=~/devstack ./stack.sh
  
 # Creates a new instance with provisioning userdata using Bash Scripts
- name: launch a compute instance
  hosts: webservers
  tasks:
    - name: launch an instance
      os_server:
        name: vm1
        state: present
        image: "Ubuntu Server 14.04"
        flavor: "P-1"
        network: "Production"
        userdata: |
          {%- raw -%}#!/bin/bash
          apt install apache2
          {% endraw %}
 
 
 #- name: install apache2
 #   apt: name=apache2 update_cache=yes state=latest
 #   sudo: yes
